# =========================================================================
# AssetsLab — 模块接口契约（依赖倒置）
# =========================================================================
# 定义各领域模块对外暴露的能力（Protocol）。
# 模块之间只依赖这里声明的接口，不依赖具体实现。
#
# 领域模块（彼此几乎独立，仅存在真实领域关系）：
#   species.py  物种模块     — 自包含，无依赖（骨架/默认参数/动作/约束数据）
#   motion.py   3D 动作 DSL 求值器（通用表达式求值，无状态）
#   render.py   3D 绘制原语（画布/骨骼/关节/头部）
#   skeleton3d.py 3D 骨架/动作引擎（读数据渲染、IK、校验支撑）
#   server.py   组装所有模块（仅 3D 端点，基于物种默认参数）
# =========================================================================

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import (
    Motion,
    MotionListItem,
    Preset,
    PresetSummary,
    SpeciesDetail,
    SpeciesListItem,
    SpeciesSkeleton,
)

# -------------------------------------------------------------------------
# 物种模块接口
# -------------------------------------------------------------------------


class SpeciesModule(Protocol):
    """物种模块对外能力：骨骼拓扑 + 动作管理。"""

    # -- 物种 CRUD --
    def list(self) -> list[SpeciesListItem]: ...
    def get(self, species_id: str) -> SpeciesDetail: ...
    def create(self, data: SpeciesSkeleton) -> str: ...
    def update(self, species_id: str, data: SpeciesSkeleton) -> str: ...
    def delete(self, species_id: str) -> str: ...

    # -- 动作管理（属于物种） --
    def list_actions(self, species_id: str) -> list[dict]: ...
    def get_action(self, species_id: str, action_id: str) -> Motion: ...
    def save_action(self, species_id: str, action_id: str, data: Motion) -> str: ...
    def delete_action(self, species_id: str, action_id: str) -> str: ...
    def find_action(self, action_id: str) -> tuple[str, Motion] | None: ...


# -------------------------------------------------------------------------
# 预设模块接口
# -------------------------------------------------------------------------


class PresetModule(Protocol):
    """预设模块对外能力：预设 = 物种实例（体型参数 + 动作参数）。"""

    def list(self) -> list[PresetSummary]: ...
    def get(self, preset_id: str) -> dict: ...
    def new_schema(self, species_id: str) -> dict: ...
    def create(self, data: Preset) -> str: ...
    def update(self, preset_id: str, data: Preset) -> str: ...
    def delete(self, preset_id: str) -> str: ...
    def build_preset_schema(self, species_id: str) -> dict: ...


# -------------------------------------------------------------------------
# 统一 API 契约（CLI 与 HTTP 共享的硬约束）
# -------------------------------------------------------------------------
# CLI（python -m assetslab.cli）与 HTTP（server.py）都依赖同一个 Api 接口：
# 新增任何操作必须在 Api 中声明，两侧实现保持一致（运行时 isinstance 校验 + 类型注解）。


@runtime_checkable
class Api(Protocol):
    """统一 API：物种 + 动作 + 预设 + 3D 渲染。CLI 与 HTTP 共用同一套接口。"""

    # -- 物种 --
    def species_list(self) -> list[SpeciesListItem]: ...
    def species_get(self, species_id: str) -> SpeciesDetail: ...
    def species_create(self, data: SpeciesSkeleton) -> str: ...
    def species_update(self, species_id: str, data: SpeciesSkeleton) -> str: ...
    def species_delete(self, species_id: str) -> str: ...
    def species_preset_schema(self, species_id: str) -> dict | None: ...
    def species_default(self, species_id: str) -> dict | None: ...
    def species_save_default(self, species_id: str, data: dict) -> str: ...

    # -- 动作 --
    def actions_list_all(self) -> list[MotionListItem]: ...
    def action_get(self, species_id: str, action_id: str) -> Motion: ...
    def action_create(self, species_id: str, data: Motion) -> str: ...
    def action_update(self, species_id: str, action_id: str, data: Motion) -> str: ...
    def action_delete(self, species_id: str, action_id: str) -> str: ...

    # -- 预设 --
    def presets_list(self) -> list[PresetSummary]: ...
    def preset_get(self, preset_id: str) -> dict: ...
    def preset_new(self, species_id: str) -> dict: ...
    def preset_create(self, data: Preset) -> str: ...
    def preset_update(self, preset_id: str, data: Preset) -> str: ...
    def preset_delete(self, preset_id: str) -> str: ...

    # -- 3D 渲染（返回 data_url / frames / gif） --
    def render_skeleton3d(self, species_id: str, *, yaw: float = 0, pitch: float = 0,
                          dist: float = 600, zoom: float = 1, pan_x: float = 0, pan_y: float = 0,
                          body: dict | None = None) -> str: ...
    def render_motion3d(self, action_id: str, *, species: str | None = None, yaw: float = 0,
                        pitch: float = 0, dist: float = 600, zoom: float = 1, pan_x: float = 0,
                        pan_y: float = 0, frame: int = 0, gif: bool = False,
                        frames: bool = False) -> dict: ...
    def render_preset3d(self, preset_ref: str, *, species: str | None = None,
                        body: dict | None = None, actions: dict | None = None,
                        action_id: str | None = None, yaw: float = 0, pitch: float = 0,
                        dist: float = 600, zoom: float = 1, pan_x: float = 0, pan_y: float = 0,
                        frame: int = 0, gif: bool = False, frames: bool = False) -> dict: ...
