#!/usr/bin/env python3
"""Export a Godot-ready artifact package under ``dist/<workflow_id>/``.

Pure Python (Pillow only): copies the verified layered frames, renders a walk
preview GIF, and writes a ``runtime_manifest.json`` that the Godot demo
consumes via ``--artifacts``.  No Godot binary is required to build artifacts.

Layout::

    dist/<workflow_id>/
    ├── atlas/
    │   ├── feet/ lower_body/ arms/ torso/     # body layers (4x8)
    │   └── head_base/ ear/ face/              # calibrated head layers (4x8)
    ├── runtime_manifest.json                  # directions, anchors, layers, meta
    ├── character_walk_4way.gif                # Pillow-composited preview
    └── README.md                              # how to run it in the Godot demo
"""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
PROTOTYPE = ROOT / "prototype"
CHIBI_ROOT = PROTOTYPE / "assets/characters/chibi"
HEAD_ROOT = PROTOTYPE / "assets/characters/rebuild_atlas_v1_runtime/male"
DEFAULT_OUTPUT = ROOT / "dist"

CELL = 64
ROWS = 4
FRAMES = 8
DIRECTIONS = ["front", "right", "back", "left"]
BODY_LAYERS = ("feet", "lower_body", "arms", "torso")
HEAD_LAYERS = ("head_base", "ear", "face")
HEAD_SOURCE_DIRS = {"head_base": "face_base_frames", "ear": "ears_frames", "face": "face_frames"}


def load_frames(root: Path, layer_dir: str) -> list[list[Image.Image]]:
    frames = []
    for row in range(ROWS):
        row_frames = []
        for frame in range(FRAMES):
            path = root / layer_dir / f"walk_row{row}_frame{frame}.png"
            if not path.exists():
                raise FileNotFoundError(f"missing layer frame: {path}")
            row_frames.append(Image.open(path).convert("RGBA"))
        frames.append(row_frames)
    return frames


def copy_frames(src_root: Path, layer_dir: str, dst: Path) -> list[Path]:
    copied = []
    for row in range(ROWS):
        for frame in range(FRAMES):
            src = src_root / layer_dir / f"walk_row{row}_frame{frame}.png"
            if src.exists():
                dst.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst / src.name)
                copied.append(dst / src.name)
    return copied


def compose(body: dict[str, list[list[Image.Image]]], head: dict[str, list[list[Image.Image]]], row: int, frame: int, offset: tuple[int, int]) -> Image.Image:
    image = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    for layer in BODY_LAYERS:
        image.alpha_composite(body[layer][row][frame])
    for layer in HEAD_LAYERS:
        image.alpha_composite(head[layer][row][frame], dest=offset)
    return image


def make_gif(frames: list[Image.Image], path: Path) -> None:
    enlarged = [f.resize((256, 256), Image.Resampling.NEAREST) for f in frames]
    enlarged[0].save(path, save_all=True, append_images=enlarged[1:], duration=100, loop=0)


def write_manifest(dist: Path, workflow_id: str, offsets: dict, files: list[str]) -> None:
    manifest = {
        "schema": "assetslab_artifact_v1",
        "workflow_id": workflow_id,
        "generator": "workflow/tools/export_artifacts.py",
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "cell_size": [CELL, CELL],
        "directions": DIRECTIONS,
        "frames_per_direction": FRAMES,
        "layer_order": list(BODY_LAYERS) + list(HEAD_LAYERS),
        "head_anchor_offsets": offsets,
        "atlas_dir": "atlas",
        "preview_gif": "character_walk_4way.gif",
        "files": sorted(files),
    }
    (dist / "runtime_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_readme(dist: Path, workflow_id: str) -> None:
    readme = f"""# AssetsLab Artifact · {workflow_id}

Generated by `workflow/tools/export_artifacts.py` (pure Python).

## Contents

- `atlas/` — layered 4×8 frames: `feet`, `lower_body`, `arms`, `torso`,
  `head_base`, `ear`, `face`.
- `runtime_manifest.json` — directions, layer order, `head_anchor_offsets`.
- `character_walk_4way.gif` — Pillow-composited preview.

## Run in the Godot demo

From the repository root, point the minimal demo at this artifact:

```bash
godot --path prototype -- --artifacts dist/{workflow_id}
```

The demo keeps interactive movement (WASD/arrows) and bomb placement (Space).
"""
    (dist / "README.md").write_text(readme, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export a Godot-ready artifact package to dist/<workflow_id>/.")
    parser.add_argument("--workflow-id", required=True, help="Artifact package name under dist/.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Dist root (default: <repo>/dist).")
    parser.add_argument("--body-root", type=Path, default=CHIBI_ROOT)
    parser.add_argument("--head-root", type=Path, default=HEAD_ROOT)
    args = parser.parse_args()

    workflow_id = args.workflow_id
    dist = args.output / workflow_id
    atlas = dist / "atlas"
    if dist.exists():
        shutil.rmtree(dist)

    files: list[str] = []
    # Body layers from the chibi runtime split.
    body = {}
    for layer in BODY_LAYERS:
        body[layer] = load_frames(args.body_root, f"{layer}_frames")
        files += [str(p.relative_to(dist)) for p in copy_frames(args.body_root, f"{layer}_frames", atlas / layer)]
    # Calibrated head layers from the rebuild runtime.
    head = {}
    for layer in HEAD_LAYERS:
        head[layer] = load_frames(args.head_root, HEAD_SOURCE_DIRS[layer])
        files += [str(p.relative_to(dist)) for p in copy_frames(args.head_root, HEAD_SOURCE_DIRS[layer], atlas / layer)]

    offsets = {}
    manifest_src = args.head_root / "runtime_manifest.json"
    if manifest_src.exists():
        offsets = json.loads(manifest_src.read_text(encoding="utf-8")).get("body_anchor_offsets", {})

    # Pillow-composited walk preview (identical layering to the Godot demo).
    frames = []
    for row in range(ROWS):
        offset = tuple(offsets.get(DIRECTIONS[row], [0, 0]))
        for frame in range(FRAMES):
            frames.append(compose(body, head, row, frame, offset))
    gif_path = dist / "character_walk_4way.gif"
    make_gif(frames, gif_path)
    files.append(gif_path.relative_to(dist).as_posix())

    write_manifest(dist, workflow_id, offsets, files)
    write_readme(dist, workflow_id)
    print(f"ARTIFACTS_EXPORT_PASS workflow_id={workflow_id} output={dist.resolve()}")
    print(f"ARTIFACT_PREVIEW={gif_path.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
